In [1]:
a = "Hi there Sam!" 
print(a.split()) 


['Hi', 'there', 'Sam!']


In [3]:
pl = "Earth" 
di = 12742 
ans="The diameter of {} is {} kilometers." 
print(ans.format(pl,di)) 


The diameter of Earth is 12742 kilometers.


In [4]:
ans = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]} 
ans['k1'][3]['tricky'][3]['target'][3] 


'hello'

In [6]:
import numpy as np
arr=np.zeros(10) 
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr_five=np.ones(10)*5 
arr_five 

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
print(np.arange(20,36,2)) 


[20 22 24 26 28 30 32 34]


In [9]:
print(np.arange(0, 9).reshape(3,3)) 


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 
print(np.concatenate((x,y))) 


[1 2 3 4 5 6]


In [11]:
import pandas as pd
dframe = pd.DataFrame(np.random.randint(0,10, size=(3,2))) 
dframe


0  1
0  5  8
1  7  6
2  6  5

In [12]:
from datetime import datetime 
pd.date_range(start="2023-01-01",end="2023-02-10").to_pydatetime().tolist() 

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2023, 1, 2, 0, 0),
 datetime.datetime(2023, 1, 3, 0, 0),
 datetime.datetime(2023, 1, 4, 0, 0),
 datetime.datetime(2023, 1, 5, 0, 0),
 datetime.datetime(2023, 1, 6, 0, 0),
 datetime.datetime(2023, 1, 7, 0, 0),
 datetime.datetime(2023, 1, 8, 0, 0),
 datetime.datetime(2023, 1, 9, 0, 0),
 datetime.datetime(2023, 1, 10, 0, 0),
 datetime.datetime(2023, 1, 11, 0, 0),
 datetime.datetime(2023, 1, 12, 0, 0),
 datetime.datetime(2023, 1, 13, 0, 0),
 datetime.datetime(2023, 1, 14, 0, 0),
 datetime.datetime(2023, 1, 15, 0, 0),
 datetime.datetime(2023, 1, 16, 0, 0),
 datetime.datetime(2023, 1, 17, 0, 0),
 datetime.datetime(2023, 1, 18, 0, 0),
 datetime.datetime(2023, 1, 19, 0, 0),
 datetime.datetime(2023, 1, 20, 0, 0),
 datetime.datetime(2023, 1, 21, 0, 0),
 datetime.datetime(2023, 1, 22, 0, 0),
 datetime.datetime(2023, 1, 23, 0, 0),
 datetime.datetime(2023, 1, 24, 0, 0),
 datetime.datetime(2023, 1, 25, 0, 0),
 datetime.datetime(2023, 1, 26, 0,

In [13]:
twod_list = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 
dframe=pd.DataFrame(twod_list,columns=["Sl.no","Name","Roll.no"]) 
dframe


Sl.no Name  Roll.no
0      1  aaa       22
1      2  bbb       25
2      3  ccc       24